In [13]:
#Processo de Gram Schimdt

import numpy as np
from scipy import linalg

def qr_gramschmidt(A):
    m, n = A.shape
    R = np.zeros((n, n))
    Q = np.empty((m, n))
    R[0, 0] = linalg.norm(A[:, 0])
    Q[:, 0] = A[:, 0] / R[0, 0]
    for k in range(1, n):
        R[:k-1, k] = np.dot(Q[:m, :k-1].T, A[:m, k])
        z = A[:m, k] - np.dot(Q[:m, :k-1], R[:k-1, k])
        R[k, k] = linalg.norm(z)
        Q[:m, k] = z / R[k, k]
    return Q, R

if __name__ == '__main__':
    
    m = 5
    n = 5
    A = np.random.randint(20000,size=(m, n))-10000
    Q, R = qr_gramschmidt(A)
    print('Matriz A\n')
    print(A) #matriz A
    print('\nMatriz Q (*)\n')
    print(Q.round(4)) #matriz Q
    print('\nMatriz R (*)\n')
    print(R.round(6)) #matriz R
    print('\n Matriz QR-A (erro) (**)')
    print((np.dot(Q,R)-A).round(8))
    print('*resultados arredondados com 6 (** 8) casas decimais para facilitar a leitura')

Matriz A

[[ 8831  2460  4509  4022  1522]
 [ 1638 -5087  9754  1470 -9669]
 [ 2604  3218 -4142 -2573 -4570]
 [ -841 -6843 -1313 -8596 -8258]
 [-9042 -3814   993  7717  -950]]

Matriz Q (*)

[[ 0.6775  0.2416  0.2286  0.4271  0.0291]
 [ 0.1257 -0.4996  0.833   0.2455 -0.0463]
 [ 0.1998  0.3161 -0.4177 -0.2368 -0.9007]
 [-0.0645 -0.6721 -0.1001 -0.6038 -0.2092]
 [-0.6937 -0.3746  0.2632  0.5802  0.3768]]

Matriz R (*)

[[13035.162676     0.        2848.893483 -2402.872045    94.939974]
 [    0.       10181.254245     0.        2310.72768   9660.583523]
 [    0.           0.       11279.254626     0.       -5221.165744]
 [    0.           0.           0.       11920.524634     0.      ]
 [    0.           0.           0.           0.       10906.019957]]

 Matrix QR-A (erro) (**)
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -0. -0. -0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
*resultados arredondados com 6 (** 8) casas decimais para facilitar a leitura


In [14]:
#Matriz de Rotação de Givens

import numpy as np
from scipy import linalg
from numpy import sin, cos, pi

def montagem_rotGivens(A,i,j):
    n = A.shape[1]
    Pij = np.identity(n)
    if(np.absolute(A[i,j])<0.1e-4):
        theta = np.pi/4
    else:
        theta = np.arctan(A[i,j]/A[j,j])

    Pij[i,i] = np.cos(theta)
    Pij[j,j] = np.cos(theta)
    Pij[i,j] = -np.sin(theta)
    Pij[j,i] = np.sin(theta)
    
    return Pij

def decompor_rotGivens(A):
    n = A.shape[1]
    
    Q = np.identity(n)
    
    for j in range(0,n-1):
        for i in range(j+1,n):
            Pt = montagem_rotGivens(A,i,j)
            
            A = np.dot(Pt,A)
            Q = np.dot(Pt,Q)
            
    return (Q.T , A)

def qr_rotGivens(A, H=None):
    n = A.shape[1]
    R = np.copy(A)
    P = np.identity(n)
    Q = np.empty(n)
    
    if(H != None):
        Pt = H
    i=0
    erro = np.inf
    
    while(erro>0.1e-8 and i < 100):
        Q ,R = decompor_rotGivens(R)            
        A = np.dot(R,Q)
        P = np.dot(P,Q)
        for j in range(0,n-1):
            erro = np.dot(R[j+1:n,j],R[j+1:n,j])
        erro = np.sqrt(erro)
        i += i
    return Q , R


if __name__ == '__main__':
    
    
    n = 5
    A = np.random.randint(20000,size=(m, n))-10000
    R = np.copy(A)
    print('Matriz A\n',A,'\n')     
    Q ,R = qr_rotGivens(A)
    print('\nMatriz Q (*)\n')
    print(Q.round(4)) #matriz Q
    print('\nMatriz R (*)\n')
    print(R.round(4)) #matriz R
    print('\n Matriz QR-A (erro) (**)')
    print((np.dot(Q,R)-A).round(8))
    print('*resultados arredondados com 6 (** 8) casas decimais para facilitar a leitura')


Matriz A
 [[ 1512 -1652  7367  9357  3789]
 [-8624 -2371 -5442  8036  7983]
 [-2660  3807  5748  3176 -3681]
 [-5336 -5434 -9985 -7385  5651]
 [ 7882 -4467 -6594  3977  2299]] 


Matriz Q (*)

[[ 0.1145  0.1959  0.9731 -0.026   0.0294]
 [-0.6532  0.2695  0.0098 -0.6837 -0.1822]
 [-0.2015 -0.4506  0.0834 -0.2079  0.8404]
 [-0.4041  0.6332 -0.0772  0.5327  0.3821]
 [ 0.597   0.5339 -0.2    -0.4526  0.3373]]

Matriz R (*)

[[ 13203.5579    121.9361   3339.0306    541.5384  -4950.0281]
 [     0.      -8503.621  -12456.1141     14.2633   9357.6922]
 [     0.          0.       9685.2834   9224.4172   2562.1991]
 [     0.          0.         -0.     -12132.153   -2822.0101]
 [     0.          0.          0.         -0.      -1501.9943]]

 Matrix QR-A (erro) (**)
[[ 0. -0. -0. -0.  0.]
 [ 0.  0. -0. -0.  0.]
 [-0.  0.  0. -0.  0.]
 [ 0. -0. -0.  0. -0.]
 [ 0.  0. -0.  0.  0.]]
*resultados arredondados com 6 (** 8) casas decimais para facilitar a leitura


In [34]:
## Transformação de Householder

import numpy as np
from scipy import linalg

def column_convertor(x):
    """
    Converts 1d array to column vector
    """
    x.shape = (1, x.shape[0])
    return x

def householder_transformation(v):
    """
    Returns Householder matrix for vector v
    """
    size_of_v = v.shape[1]
    e1 = np.zeros_like(v)
    e1[0, 0] = 1
    vector = linalg.norm(v) * e1
    if v[0, 0] < 0:
        vector = - vector
    u = (v + vector).astype(np.float32)
    H = np.identity(size_of_v) - ((2 * np.matmul(np.transpose(u), u)) / np.matmul(u, np.transpose(u)))
    return H

def qr_step_factorization(q, r, iter, n):
    """
    Return Q and R matrices for iter number of iterations.
    """
    v = column_convertor(r[iter:, iter])
    Hbar = householder_transformation(v)
    H = np.identity(n)
    H[iter:, iter:] = Hbar
    r = np.matmul(H, r)
    q = np.matmul(q, H)
    return q, r

def main():
    m, n = (5,5)
    A = np.random.randint(10000, size=(m,n))-10000
    print('Matriz A \n', A)
    Q = np.identity(n)
    R = A.astype(np.float32)
    for i in range(min(n, m)):
        # For each iteration, H matrix is calculated for (i+1)th row
        Q, R = qr_step_factorization(Q, R, i, n)
    min_dim = min(m, n)
    R = R[:min_dim, :min_dim]

    print('Matriz R')
    print(R.round(2), '\n')
    print('Matriz Q')
    print(Q.round(6))
    print('Matriz erro\n')
    print((A-np.dot(Q,R)).round(8))


if __name__ == "__main__":
    main()

Matriz A 
 [[-1603 -3091 -2922 -2106 -4063]
 [-7715 -4090 -8197 -7283 -1596]
 [ -166 -1683 -6090   -81 -6713]
 [-8632  -386 -9957 -8778 -6879]
 [-5147 -6392 -4206 -1893 -3203]]
Matriz R
[[12771.9   5717.25 13821.9  11360.31  7501.3 ]
 [   -0.   -6118.38  -737.45  2129.31 -1736.8 ]
 [    0.      -0.    6169.33  1014.63  6943.98]
 [   -0.      -0.      -0.   -1871.     744.63]
 [   -0.       0.      -0.      -0.   -3693.25]] 

Matriz Q
[[-0.12551   0.387918 -0.146069  0.725793  0.534467]
 [-0.604061  0.10402   0.037114  0.363354 -0.700633]
 [-0.012997  0.262928 -0.926593 -0.238881 -0.122728]
 [-0.675859 -0.56846  -0.167694 -0.14994   0.411661]
 [-0.402994  0.668148  0.300983 -0.51152   0.19731 ]]
Matriz erro

[[ 1.7834e-04  3.5480e-05  2.9366e-04  2.9865e-04  1.2185e-04]
 [ 7.5660e-04  5.9864e-04  5.9471e-04  7.1320e-04 -1.7043e-04]
 [ 6.3800e-06 -4.5610e-05 -8.8893e-04 -1.3516e-04 -7.9610e-04]
 [ 6.4810e-05 -3.8480e-05  1.0917e-04  3.6470e-05  2.6891e-04]
 [ 3.2693e-04  2.7891e-04  5.68